/*
  Warnings:

  - The values [BLOG,ECONOMIC,MOVIE,THRILLER,ROMANCE] on the enum `Category` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "Category_new" AS ENUM ('ACTION', 'ADVENTURE', 'ADVERTISING', 'ANIMATION', 'ANIME', 'ART', 'ARTS_AND_ENTERTAINMENT', 'AUTOS_AND_VEHICLES', 'BANKING', 'BARS', 'BEAUTY', 'BEAUTY_AND_FITNESS', 'BETTING', 'BLOCKCHAIN', 'BLOGGING', 'BOOKS', 'BOOKS_AND_LITERATURE', 'BUSINESS', 'BUSINESS_AND_FINANCE', 'CAREERS_AND_EMPLOYMENT', 'CHARITY', 'CHILDREN', 'CLOUD_COMPUTING', 'CLOUD_STORAGE', 'COLLECTIBLES', 'COMEDY', 'COMMUNITY', 'COMPUTERS_AND_ELECTRONICS', 'CREDIT', 'CULTURE', 'CUSTOMER_SERVICE', 'DATING', 'DESIGN', 'DIGITAL_ART', 'DIGITAL_STREAMING', 'DIY', 'DRAMA', 'ECOMMERCE', 'EDUCATION', 'ELECTRONICS', 'EMAIL', 'ENTERTAINMENT', 'ENVIRONMENT', 'EVENT', 'FAMILY_AND_PARENTING', 'FASHION', 'FINANCE', 'FITNESS', 'FOOD', 'FOOD_AND_DRINK', 'GAMING', 'GARDENING', 'GOVERNMENT', 'HEALTH', 'HEALTH_AND_WELLNESS', 'HOBBIES_AND_LEISURE', 'HOSPITALITY', 'HISTORY', 'HOME', 'HOME_AND_GARDEN', 'HUMOR', 'INTERNET_AND_TELECOM', 'INVESTMENT', 'JOURNALISM', 'LAW_AND_GOVERNMENT', 'LIFESTYLE', 'LITERATURE', 'LIVE_STREAMING', 'LOCAL_SEARCH', 'MAPS', 'MARKETING', 'MEDIA', 'MEDICAL', 'MUSIC', 'NATURE', 'NEWS', 'NON_PROFIT', 'NUTRITION', 'ONLINE_COMMUNITIES', 'ONLINE_MARKETPLACE', 'OPEN_SOURCE', 'PARENTING', 'PERSONAL_DEVELOPMENT', 'PEOPLE_AND_SOCIETY', 'PETS', 'PETS_AND_ANIMALS', 'PHILOSOPHY', 'PHOTOGRAPHY', 'POLITICS', 'PROGRAMMING', 'PROJECT_MANAGEMENT', 'PSYCHOLOGY', 'REAL_ESTATE', 'RECRUITMENT', 'REFERENCE', 'RELIGION', 'RESEARCH', 'RESTAURANTS', 'SCIENCE', 'SEARCH_ENGINES', 'SELF_HELP', 'SHOPPING', 'SOCIAL_MEDIA', 'SOFTWARE', 'SPORTS', 'TECHNOLOGY', 'TELEVISION', 'THEATER', 'TRAVEL', 'TOURISM', 'UNCATEGORIZED', 'VIDEO', 'VIDEO_PRODUCTION', 'VIDEO_SHARING', 'VIRTUAL_REALITY', 'VLOGS', 'WEATHER', 'WEB_DESIGN', 'WEB_DEVELOPMENT', 'WEB_HOSTING', 'WEDDINGS', 'WELLNESS', 'WRITING');
ALTER TABLE "Idea" ALTER COLUMN "categories" TYPE "Category_new"[] USING ("categories"::text::"Category_new"[]);
ALTER TYPE "Category" RENAME TO "Category_old";
ALTER TYPE "Category_new" RENAME TO "Category";
DROP TYPE "Category_old";
COMMIT;
